### ISSUE TITLE
no resut shown when I use pglyco [Added by ZWF: folders containing Non-English characters]

### ISSUE THREAD

**Issue by ShenXipeng** [pFindStudio/pGlyco2#1]
the resut *.TXT was empty and the report seems like:
Converting N in N-X-S/T/C to J
----Source fasta = D:\TemporaryData\糖肽分析\human.fasta
----Target fasta = D:\TemporaryData\糖肽分析\human.fasta.N2J

	  *********************************************
	 /       pParse2.0 (x64) from pFind Studio     \
	/        Email  :  pfind@ict.ac.cn              \
	\        Website:  http://pfind.ict.ac.cn       /
	  *********************************************

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract D:\TemporaryData\糖肽分析\ABQ-glycopeptide-A.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Output files>: 100.00%
[pXtract] Output Files Completed!
[pXtract] == == == Time elapsed: 141.246s. == == ==
[pParse] MS1list completes. 
[pParse] Processing ABQ-glycopeptide-A.MS1 
[pParse] Loading MS1 and MS2 files... 
[pParse] Loading MS1 Spectra Number: 16942 
[pParse] Loading MS2 Spectra Number: 16059 
[pParse] Writing MS1 to PF... 

[pParse] <Exporting HCDFT>: 100%

[pParse] Evaluting by the classifier... 
[pParse] Filtering by the threshold... 

[pParse] <Writing MGF>: 100%
[pParse] Writing CSV... 
[pParse] Releasing resources... 
[pParse] Saving CSV to disk... 
[pParse] Exported 37654 precursors. 
[pParse] Found 0 duplicate scans. 
[pParse]  == == == Time elapsed: 255 seconds. == == == =  
*****************************************************
*                                                   *
*             * Welcome to pGlyco2 *                *
*                                                   *
*              * pglyco@ict.ac.cn *                 *
*                                                   *
*****************************************************

[pGlyco Info] License will be expired in 2019/01/01
[pGlyco Info] Loading glycan database ...
[pGlyco Info] Ion Indexing ...
CFastaReader() in CFastaReader:
Process 1: [Complete] 100% [==================================================]
[pGlyco Info] Estimating FDR ...
Could not open D:\TemporaryData\glyco\pGlyco_task_2018-01-06-01\process1\pGlycoDB-GP.txt!
[pGlyco Info] Inferring proteins ...
Reading pGlyco results ...
[pGlyco Info] Combining all results to:
 ----D:\TemporaryData\glyco\pGlyco_task_2018-01-06-01\pGlycoDB-GP-FDR-Pro.txt
[pGlyco Info] Task Complete!

**Comment by jalew188** [comment]
**Do not put the fasta file into the folder that contains Chinese characters**, because pGlyco2 GUI may have different Chinese encoding comparing with your Windows system. Generally, putting raw files and output folder into "non-English" folder is not recommended.

**Comment by ShenXipeng** [comment]
I have changed the chinese characters to English.  But there is still no resut about glycopeptides.
The file pGlycoDB-GP-FDR-Pro.txt is empty. Is it caused by Raw data?
The report :
Converting N in N-X-S/T/C to J
----Source fasta = D:\TemporaryData\glycopeptides_data\human.fasta
----Target fasta = D:\TemporaryData\glycopeptides_data\human.fasta.N2J

[pParse] Calling pXtract to export MS1 and MS2 files... 
[pXtract] The software will expire in 01/01/2019
[pXtract] Begin to extract D:\TemporaryData\glycopeptides_data\ABQ-glycopeptide-B_180104153918.raw
[pXtract] pXtract tries to use MSFileReader 
[pXtract] <Output files>: 100.00%
[pXtract] Output Files Completed!
[pXtract] == == == Time elapsed: 132.507s. == == ==
[pParse] MS1list completes. 
[pParse] Processing ABQ-glycopeptide-B_180104153918.MS1 
[pParse] Loading MS1 and MS2 files... 
[pParse] Loading MS1 Spectra Number: 17951 
[pParse] Loading MS2 Spectra Number: 14075 
[pParse] Writing MS1 to PF... 

[pParse] <Exporting HCDFT>: 100%

[pParse] Evaluting by the classifier... 
[pParse] Filtering by the threshold... 

[pParse] <Writing MGF>: 100%
[pParse] Writing CSV... 
[pParse] Releasing resources... 
[pParse] Saving CSV to disk... 
[pParse] Exported 33158 precursors. 
[pParse] Found 0 duplicate scans. 
[pParse]  == == == Time elapsed: 190 seconds. == == == =  

[pGlyco Info] License will be expired in 2019/01/01
[pGlyco Info] Loading glycan database ...
[pGlyco Info] Ion Indexing ...
[pGlyco Info] D:\TemporaryData\glycopeptides_data\ABQ-glycopeptide-B_180104153918_HCDFT.mgf
Process 1: [I.D.] 100.0% [==================================================]
[pGlyco Info] D:\TemporaryData\glycopeptides_data\ABQ-glycopeptide-B_180104153918_HCDFT.mgf finished!
Process 1: [Complete] 100% [==================================================]
[pGlyco Info] Estimating FDR ...
Fitting glycan part ...
target GlyScore pep is none
Fitting peptide part ...
[pGlyco Info] Inferring proteins ...
Reading pGlyco results ...
[pGlyco Info] Combining all results to:
 ----D:\TemporaryData\glyco\pGlyco_task_2018-01-07-2\pGlycoDB-GP-FDR-Pro.txt
[pGlyco Info] Task Complete!

**Comment by jalew188** [comment]
@ShenXipeng It seems that pGlyco2 ran successfully on your computer, but no glycopeptides were identified. Checking the following reasons that may help:

1. Is the protein database correct?

2. Does the MS2 scan range include the 138 oxonium ion? Someone may set the scan range starting from 200 Th, but pGlyco2 needs the 138 ion to determine if an MS2 spectrum is a glycopeptide spectrum. 

3. Is the AGC value large enough or the max injection time long enough (~100ms for glycopeptide)? These settings ensure us to obtain the GP spectra as good as possible.

You can download sample raw files from PRIDE ([download link](https://www.ebi.ac.uk/pride/archive/projects/PXD005565/files), Fission Yeast), check the parameters and check how pGlyco runs.

Hope this helps!!

**Comment by jalew188** [comment]
@ShenXipeng In the **_pGlycoTask_**/process1 folder, there is a file named summary.txt, it records how many MS2 scans are glycopeptide scans determined by pGlyco2.

**Comment by ShenXipeng** [comment]
In my rawdata, In the pGlycoTask/process1 folder, summary.txt, the Oxonium Contained Scans = 19; but, the pGlycoDB-GP-FDR-Pro.txt file was empty.
Then I tryed two rawdata from PRIDE archive, about EPO, use hunam.fasta directly download from NCBI. This time the Oxonium Contained Scans = 0, and still the pGlycoDB-GP-FDR-Pro.txt file was empty.
What should I do?

**Comment by ShenXipeng** [comment]
For the MS parameters, MS2 start from 100 M/Z, max injection time 60ms; The database seems right.

![default](https://user-images.githubusercontent.com/35022470/34658179-c0a65008-f467-11e7-8720-d046cca45ed1.png)

**Comment by jalew188** [comment]
If "Oxonium Contained Scans = 0", that means pGlyco2 thinks no glycopeptide spectra in this raw file, so of cause no results. In this case, I can't help you further. 

For your own raw file, "Oxonium Contained Scans = 19", that's too few!! If the quality of these 19 GP spectra is not good enough, pGlyco2 will not output them into the result file (check pGlycoDB-GP.txt). 

For my own data, for example, the fission yeast data sets,  "---- # Total MS2 Scans = 162248;  ---- # Oxonium Contained Scans = 7754; ---- Ratio = 0.047791". 

So I think the first thing you should try is to increase the triggering rates of glycopeptide precursors in your mass spec settings (for example, changing the MS1 scan range to 700~2000 Th). By the way, stepped-CE is always preferred.

**Comment by ShenXipeng** [comment]
I have tryed your data this afternoon. There are quite a lot of glycopeptides in the result. Now I am pretty sure that the problem caused by my poor rawdata. 
Thanks for your patient!

**Comment by jalew188** [comment]
@ShenXipeng Hope we can make it better together!
