### ISSUE TITLE
Please add m/z and charge in the output text file 

### ISSUE THREAD

**Issue by go2pGlyco** [pFindStudio/pGlyco2#12]
Dear pGlyco team,

I really would like to have m/z and charge of each matched glycopeptide in the output text file. That will be much easier when we want to do PRM of the interested glycopeptides for further analysis.

Thanks!
Haidi

**Comment by jalew188** [comment]
@go2pGlyco you can use https://github.com/pFindStudio/pGlyco2/blob/master/bug_fix_list/fixed_file_2018/pGlycoDB.exe, 
in which m/z and charge are added into the output file.
