### ISSUE TITLE
target GlyScore pep is none

### ISSUE THREAD

**Issue by congcongW** [pFindStudio/pGlyco2#18]
I wonder if the pGlyco2 can identifi glycopeptide deglycosylated by PNGase F in 18O-water. there are Deamidated_18O(1)[Q] but no Deamidated_18O(1)[N] in the step of Identification.Thank you!

when I select the Deamidated_18O(1)[Q], output show :
pGlyco Info] License will be expired in 2019/01/01
[pGlyco Info] Loading glycan database ...
[pGlyco Info] Ion Indexing ...
[pGlyco Info] G:\WCC\pGlyco\20180811_NGlyco_8_HCDFT.mgf
Process 1: [I.D.] 100.0% [==================================================]
[pGlyco Info] G:\WCC\pGlyco\20180811_NGlyco_8_HCDFT.mgf finished!
Process 1: [Complete] 100% [==================================================]
[pGlyco Info] Estimating FDR ...
Fitting glycan part ...
target GlyScore pep is none
Fitting peptide part ...
[pGlyco Info] Inferring proteins ...
Reading pGlyco results ...
[pGlyco Info] Combining all results to:
 ----C:\Users\Acer\Documents\pGlyco\pGlyco_task_2018-11-27-11-45-55\pGlycoDB-GP-FDR-Pro.txt
[pGlyco Info] Task Complete!

and the summary
# Total MS2 Scans = 66528
---- #   Contained Scans = 98
---- Ratio = 0.00147306

**Comment by jalew188** [comment]
@congcongW It seems that there are few oxonium contained MS/MS spectra for glycopeptide identification.

**Comment by congcongW** [comment]
I know pGlyco is for intact glycopeptides,including both the glycan and the peptide. But could pGlyco used for only glycosite-containing peptides not intact N-glycopeptides ?   MS/MS acquisition only include the peptide. Because N-linked glycans been released from glycopeptide by PNGase F digestion in experimental procedures.Thank you！

**Comment by jalew188** [comment]
@congcongW Not necessary, peptide search engines can search de-glycosylated peptides. You can use pFind or MaxQuant.
