### ISSUE TITLE
gLabel glycan fragment bars

### ISSUE THREAD

**Issue by abondt** [pFindStudio/pGlyco2#21]
In an annotated spectrum the height of the bars that gLabel put in there do not match the actual fragment ion intensities. This is in particular here for the 138, 168, 186 and 204 in this spectrum. Why is that?

Raw data points plot:
![image](https://user-images.githubusercontent.com/31669537/49945849-0ab36280-feee-11e8-83df-6d8460be6376.png)

Output gLabel:
![image](https://user-images.githubusercontent.com/31669537/49945582-8365ef00-feed-11e8-8b54-2020e61b801f.png)

**Comment by jalew188** [comment]
@abondt They are too high to make signal Y and b/y ions visible (see the relative intensity axis), so we truncate them.
