### ISSUE TITLE
add new protease

### ISSUE THREAD

**Issue by lonelu** [pFindStudio/pGlyco2#24]
We used a protease Glu-C, which cleaves at the C-terminus of either aspartic or glutamic acid residues. (https://www.promega.com/resources/protocols/product-information-sheets/n/gluc-sequencing-grade-protocol/)
I add "name32=GluC_DE-C /n GluC_DE-C=DE _ C 0" into enzyme.ini, but it does not work. What should I do?

**Comment by jalew188** [comment]
@lonelu "total=31"-->"total=32" at line 2 in enzyme.ini?

**Comment by lonelu** [comment]
It worked. Thanks.
