### ISSUE TITLE
About customer glycan database design

### ISSUE THREAD

**Issue by glycohezhu** [pFindStudio/pGlyco2#26]

**Comment by glycohezhu** [comment]
Hi Sir, thank you for your effort in developing pglyco. 
1) I wonder how did you guys design the glycan database. Is there a code or other program to do this?  Actually, I carefully check the glycan database. If you manually do it, that should be a huge work. Besides the bracket to define the specific glycan structure, there is also a lot of theoretical glycan fragmentation ions.  
2) Could I define a new monosaccharide in the database?
3) Could I remove the bracket for glycan composition and just define the composition like H5N4F1A1?
4) Could I remove all the theoretical glycan fragmentation ions in the data base?

**Comment by jalew188** [comment]
@glycohezhu Current version of pGlyco does not support custom glycans, so the answers for your 4 questions are NO.

**Comment by glycohezhu** [comment]
@jalew188 Got it, Dr. Zeng. Thank you.
