### ISSUE TITLE
Could pGlyco output more information for identified glycopeptides?

### ISSUE THREAD

**Issue by pfangpGlyco** [pFindStudio/pGlyco2#3]
1.	In the output spectrum, we can see the mapped fragment ions clearly, likewise, could pGlyco output the information of the fragment ions in text files, including the type of the fragment ions, m/z, z, intensity and relative intensity? This will be useful for researchers to know the mapped ions and analyze data.
2.	For the column ”GlyIonRatio” and “PepIonRatio”, I’m not sure how many theoretical fragment ions and what type of the ions were considered by the software for “gly” and “pep”, respectively. For example, y ions with short glycans, whether it belongs to  “gly” or “pep”. Could you give the information of the theoretical fragment ions type of the identified peptides and their Mass in a text files and labelled the matched ones?

**Comment by jalew188** [comment]
@pfangpGlyco 
1. I am developing newest gLabel which will have this new feature.

2. These "IonRatio" outputs are for debugging, not for users. You can use gLabel to determine whether a match is good or not.

**Comment by jalew188** [comment]
See #12
