### ISSUE TITLE
与结果文件相关的问题

### ISSUE THREAD

**Issue by ylj7** [pFindStudio/pGlyco2#9]
1.结果文件中的Rank这一栏代表的是什么意思呢？
2.结果文件中的GlyID是什么意思呢？是该糖在GlycomeDB中的编号？
3.结果文件中的GlyFrag是什么意思呢？
4.结果文件中的GlyIonRatio是什么意思呢
5.结果文件中的PepIonRatio是什么意思呢
6.结果文件中的GlyDecoy这一栏代表的是什么意思呢,0代表的是什么意思呢？
7.结果文件中的PepDecoy这一栏代表的是什么意思呢
8.结果文件中的TotalFDR是GlycanFDR和PeptideFDR的总和吗？
谢谢您的解答

**Comment by jalew188** [comment]
这几个信息大家都不要太关注，它们一般是用于计算FDR的中间结果。

比如Rank一般输出是1，表示这张谱图中某条糖肽的匹配打分排名是多少。

GlyFrag是这条糖链的所有理论碎片离子。

PepDecoy和GlyDecoy都必须为0，否则鉴定结果肯定是错误的。

TotalFDR不是简单的求和，有公式计算，具体可以看pGlyco 2.0文章。
